---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soup
spec:
  template:
    spec:
      containers:
        - name: soup
          command: /usr/local/bin/dlv
          args:
            - --listen=:40000
            - --headless=true
            - --api-version=2
            - exec
            - /app/bin/soup
            - --
            - sync
            - serve
            - https://tools.adidas-group.com/bitbucket/scm/rcs/origo-deployments.git
          ports:
            - containerPort: 40000
              name: debug