apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../bases/tools/soup

patchesStrategicMerge:
  - command.yaml

transformers:
  - instanceLabels.yaml
  - prefixSuffixTransformer.yaml
  - prefixSuffixSecretTransformer.yaml

images:
  - name: registry.tools.3stripes.net/ebtpc-commons/soup
    newTag: 1.10.0
